apiVersion: v1
kind: Pod
metadata:
  name: cic-vpx
  labels:
    app: cic-vpx
spec: 
      serviceAccountName: loadbalancer
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.7.6"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "10.102.216.166"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "YES"
         - name: "NS_USER"
           value: "nsroot"
         - name: "NS_PASSWORD"
           value: "pwd123456"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "DEBUG"
        args:
          - --ingress-classes
            vpx
          - --feature-node-watch
            false
          - --ipam
            citrix-ipam-controller
        imagePullPolicy: IfNotPresent
