
apiVersion: v1
kind: Service
metadata:
  name: lb-service-guestbook
  labels:
    app: lb-service-guestbook
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: frontend
    targetPort: 80
#  - port: 6379
#    protocol: TCP
#    name: guestbook
#    targetPort: 6379
  selector:
    app: guestbook
    tier: frontend

